### ISSUE TITLE
Add CDN Identification Rule

### ISSUE THREAD

**Issue by hanfuyunxi** [SukkaLab/cdn#25]
- CNAME: `*.w.cdngslb.com.`
- Description: `阿里云CDN https://www.aliyun.com/product/cdn`

- CNAME: `*.site.nscloudwaf.com.`
- Description: `绿盟云WAF https://cloud.nsfocus.com`

- CNAME: `*.2cname.com.`
- Description: `DDOS.COM网堤安全 https://www.ddos.com`

- CNAME: `*.pathx.ucloudgda.com.`
- Description: `UCloud PathX/Rome https://www.ucloud.cn/site/product/rome.html`

- CNAME: `*.ucloud.com.cn.`
- Description: `UCloud 云分发UCDN https://www.ucloud.cn/site/product/ucdn.html`

**Comment by SukkaW** [comment]
LGTM, and PR is welcome.
